fitur pengunguman done, dan homepage admin serta beberapa fitur
tekno-HMTC/web-elearning pull request #6
Opened 2019-04-20 16:38 UTC by catehulu

2019-04-20 16:44 UTC, GSculerlor commented
pengunguman apaan anjir wkwk

2019-04-20 16:45 UTC, GSculerlor requested changes
https://kbbi.web.id/pengumuman

penguguman -> pengumuman

2019-04-20 16:48 UTC, catehulu commented
Anjir baru sadar :v

2019-04-20 17:28 UTC, catehulu commented
ok bisa di cek lg

2019-04-22 18:11 UTC, GSculerlor approved these changes

2019-04-22 18:11 UTC, merged